# Generated by Django 5.2.13 on 2026-04-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Wedding Program Outline 📅', max_length=200)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='program/')),
            ],
        ),
        migrations.DeleteModel(
            name='ProgramEvent',
        ),
    ]
