# Generated by Django 5.2.13 on 2026-04-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveStoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='about',
            name='subtitle',
            field=models.CharField(default='A journey written by fate', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='Our Love Story', max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='embed_url',
            field=models.TextField(help_text='Paste Google Maps embed link'),
        ),
    ]
