# Generated by Django 5.2.13 on 2026-05-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_about_image_remove_about_subtitle_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Odoyewu Wedding', max_length=200)),
                ('bride_name', models.CharField(max_length=100)),
                ('groom_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('hero_video', models.FileField(blank=True, null=True, upload_to='site/videos/')),
                ('background_music', models.FileField(blank=True, null=True, upload_to='site/music/')),
                ('theme_color', models.CharField(default='#d63384', max_length=20)),
                ('countdown_title', models.CharField(default='Countdown to Forever', max_length=200)),
            ],
        ),
    ]
