# Generated by Django 5.2.13 on 2026-05-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
